### ISSUE TITLE
能否用于其他数据集

### ISSUE THREAD

**Issue by swjtulinxi** [juhongm999/hpf#3]
你好，我是做遥感图像匹配的，请问这个方法能否用于遥感图像的匹配，数据集应该怎么制作啊

**Comment by juhongm999** [comment]
Yes this method can be used for the task of remote sensing image matching but you must change some part of the beam search code (algorithm 1) accordingly to find an optimal layer combination for the target task. 
Instead of PCK used in semantic correspondence task, use evaluation metrics used in the remote sensing image matching task.
